Feature/juan pulido/jumping from a wall
Loko24/Plataformas pull request #11
Opened 2023-04-30 21:20 UTC by JuanPPulido

It's complete

2023-05-01 15:20 UTC, Loko24 requested changes

2023-05-01 15:20 UTC, Loko24 commented on Assets/Scripts/Movement.cs
Private variables should start with _ (_speed)

2023-05-01 18:09 UTC, JuanPPulido commented on Assets/Scripts/Movement.cs
Ready

2023-05-02 20:02 UTC, Nik-Stevens approved these changes
Approved

2023-05-02 20:06 UTC, Nik-Stevens approved these changes
Approved

2023-05-02 23:54 UTC, daniel374 approved these changes

2023-05-02 23:57 UTC, Loko24 approved these changes

2023-05-03 01:33 UTC, merged