AudioManagerLevel1
Loko24/Plataformas pull request #8
Opened 2023-04-25 05:05 UTC by Nik-Stevens

Se creó un script que llama configura los audios, se agregaron 2 archivos de sonido para prueba
Se crearon dos GameObject, uno el AudioManager para llamar a las funciones de Audio y el segundo es El GameObject que contiene los audios

2023-04-25 15:12 UTC, Loko24 requested changes
Fix private variables with underscore before name it, fix else condition

2023-04-25 15:12 UTC, Loko24 commented on Assets/Scripts/AudioManager.cs
Fix else condition

2023-04-26 03:40 UTC, Nik-Stevens commented
I added the fixes 
The Else condition was eleminated and a Method was changed to English

2023-04-27 17:39 UTC, Loko24 approved these changes

2023-04-28 03:49 UTC, JuanPPulido approved these changes
It's ready

2023-04-28 03:49 UTC, merged